// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqoALYN8cnZPIe3LW4zNmncVH9Riaq1OA',
    appId: '1:396508899208:web:98d9887b0c28aa7225bc3d',
    messagingSenderId: '396508899208',
    projectId: 'webrtc-project-276b1',
    authDomain: 'webrtc-project-276b1.firebaseapp.com',
    storageBucket: 'webrtc-project-276b1.appspot.com',
    measurementId: 'G-0XH7L41TD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMMk0ad3ZNABW9eyuaVjvdloIvmlKwSDQ',
    appId: '1:396508899208:android:a605f35a1208f17125bc3d',
    messagingSenderId: '396508899208',
    projectId: 'webrtc-project-276b1',
    storageBucket: 'webrtc-project-276b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8oA6im6PFW96zA_cp12ZAbVOCiuZR54',
    appId: '1:396508899208:ios:a2536aea0a57f24025bc3d',
    messagingSenderId: '396508899208',
    projectId: 'webrtc-project-276b1',
    storageBucket: 'webrtc-project-276b1.appspot.com',
    iosBundleId: 'com.example.webrtcFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz8oA6im6PFW96zA_cp12ZAbVOCiuZR54',
    appId: '1:396508899208:ios:a2536aea0a57f24025bc3d',
    messagingSenderId: '396508899208',
    projectId: 'webrtc-project-276b1',
    storageBucket: 'webrtc-project-276b1.appspot.com',
    iosBundleId: 'com.example.webrtcFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqoALYN8cnZPIe3LW4zNmncVH9Riaq1OA',
    appId: '1:396508899208:web:9d4bf34959c230bf25bc3d',
    messagingSenderId: '396508899208',
    projectId: 'webrtc-project-276b1',
    authDomain: 'webrtc-project-276b1.firebaseapp.com',
    storageBucket: 'webrtc-project-276b1.appspot.com',
    measurementId: 'G-9PMMDN8EQ5',
  );
}
